language: java

jdk: openjdk11

#script: mvn clean verify
# whitelist
#branches:
#  only:
#    - master

cache:
  directories:
    - $HOME/.m2

notifications:
    slack: pathwaycommons:EDRQfFuGFr8Xn93M5xNMPVRB
