package org.biopax.validator.rules;


import org.biopax.paxtools.model.level3.RelationshipXref;
import org.biopax.paxtools.model.level3.UnificationXref;
import org.biopax.validator.impl.AbstractRule;
import org.biopax.validator.utils.BiopaxValidatorUtils;
import org.springframework.stereotype.Component;

/**
 * Checks whether more than one objects have the same 
 * UnificationXref, which violates {@link UnificationXref} semantics,
 * unless these objects are, in fact, equivalent 
 * (despite their URIs are different)
 * 
 * Although this rule is easy to check, auto-fixing is not that straightforward!
 * 
 * We could replace the {@link UnificationXref} xref with new {@link RelationshipXref}
 * (with the same db/id) for a pair of parent objects, such as, 
 * when the problematic unification xref is removed/replaced:
 * - have different/incompatible BioPAX type, - may fix (unsafe), but it may 
 * be ok, e.g., for CVs;
 * - are equivalent, i.e., they were also equivalent before, -  do nothing; 
 * other rules may merge them;
 * - are not equivalent but used to be equivalent, -  do fix for sure;
 * - are not equivalent, were not equivalent, but have the same type - fix (unsafe);
 * It becomes hard to tell how to fix if there are more than two parents 
 * and various types...
 * 
 * This rule won't fix, for it's unsafe; a data provider should take the warnings 
 * generated by this rule quite seriously and fix their BioPAX exporter.
 * 
 * @author rodche
 */
@Component
public class SharedUnificationXrefRule extends AbstractRule<UnificationXref> {

	public boolean canCheck(Object thing) {
		return thing instanceof UnificationXref;
	}
    
	public void check(UnificationXref x, boolean fix) {
        if(x.getXrefOf().size()>1) {
        	final String uriListAsString = BiopaxValidatorUtils.getIdListAsString(x.getXrefOf());
				error(x, "shared.unification.xref", false, uriListAsString);
        }
    }

}
